version: '3.8'

services:
  db:
    image: mongo
    container_name: db
    restart: always
    ports:
      - 27017:27017
    hostname: logindb

  api:
    image: node:latest
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    container_name: api
    ports:
      - 4000:4000
    command: >
      sh -c "npm install && npm install cors && npm start"
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: react_client
    ports:
      - "80:80"
    depends_on:
      - api
